### ISSUE TITLE
provide guidance for intentionally non-dereferencable URIs

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/rfc7807bis#21] opened 2021-06-01 14:35 UTC
#11 provides good guidance in terms of probably bets avoiding relative URIs. what about also providing guidance for people who intentionally want to use non-dereferencable URIs for `type` or `instance`? should we add some guidance for this as well? we had some discussion around `tag` URIs in #11 and there are other possibilities as well. but the main question is: if somebody never intends to use dereferencable URIs for `type` or `instance`, should we mention that and provide guidance?

**Comment by mnot** [comment] 2021-07-14 05:22
Is this a duplicate of #13?

**Comment by pimterry** [comment] 2021-07-28 10:21
I think this is indeed a duplicate

**Comment by mnot** [comment] 2021-07-29 02:02
Closing for now; if there's a reason to distinguish it we can reopen.

**Closed by mnot** 2021-07-29 02:02 UTC
